<?php
/**
 * EnterpriseAccountPayOrderAccountPaymentRequestDtoParam
 *
 * PHP version 5
 *
 * @category Class
 * @package  Fy\Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 账户
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Fy\Yeepay\Yop\Sdk\Service\Account\Model;

use \ArrayAccess;
use Fy\Yeepay\Yop\Sdk\Model\ModelInterface;
use Fy\Yeepay\Yop\Sdk\Utils\ObjectSerializer;

/**
 * EnterpriseAccountPayOrderAccountPaymentRequestDtoParam Class Doc Comment
 *
 * @category Class
 * @description 方法签名第0个参数，请自行修改arg0等参数的名字
 * @package  Fy\Yeepay\Yop\Sdk\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseAccountPayOrderAccountPaymentRequestDtoParam implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EnterpriseAccountPayOrderAccountPaymentRequestDtoParam';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'appKey' => 'string',
        'yopMerchantNo' => 'string',
        'parentMerchantNo' => 'string',
        'merchantNo' => 'string',
        'payerMerchantNo' => 'string',
        'marketingProductCode' => 'string',
        'orderInfo' => '\Fy\Yeepay\Yop\Sdk\Service\Account\Model\EnterpriseAccountPayOrderOrderInfoDtoParam',
        'merchantRequestIp' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'appKey' => null,
        'yopMerchantNo' => null,
        'parentMerchantNo' => null,
        'merchantNo' => null,
        'payerMerchantNo' => null,
        'marketingProductCode' => null,
        'orderInfo' => null,
        'merchantRequestIp' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'appKey' => 'appKey',
        'yopMerchantNo' => 'yopMerchantNo',
        'parentMerchantNo' => 'parentMerchantNo',
        'merchantNo' => 'merchantNo',
        'payerMerchantNo' => 'payerMerchantNo',
        'marketingProductCode' => 'marketingProductCode',
        'orderInfo' => 'orderInfo',
        'merchantRequestIp' => 'merchantRequestIp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'appKey' => 'setAppKey',
        'yopMerchantNo' => 'setYopMerchantNo',
        'parentMerchantNo' => 'setParentMerchantNo',
        'merchantNo' => 'setMerchantNo',
        'payerMerchantNo' => 'setPayerMerchantNo',
        'marketingProductCode' => 'setMarketingProductCode',
        'orderInfo' => 'setOrderInfo',
        'merchantRequestIp' => 'setMerchantRequestIp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'appKey' => 'getAppKey',
        'yopMerchantNo' => 'getYopMerchantNo',
        'parentMerchantNo' => 'getParentMerchantNo',
        'merchantNo' => 'getMerchantNo',
        'payerMerchantNo' => 'getPayerMerchantNo',
        'marketingProductCode' => 'getMarketingProductCode',
        'orderInfo' => 'getOrderInfo',
        'merchantRequestIp' => 'getMerchantRequestIp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['appKey'] = isset($data['appKey']) ? $data['appKey'] : null;
        $this->container['yopMerchantNo'] = isset($data['yopMerchantNo']) ? $data['yopMerchantNo'] : null;
        $this->container['parentMerchantNo'] = isset($data['parentMerchantNo']) ? $data['parentMerchantNo'] : null;
        $this->container['merchantNo'] = isset($data['merchantNo']) ? $data['merchantNo'] : null;
        $this->container['payerMerchantNo'] = isset($data['payerMerchantNo']) ? $data['payerMerchantNo'] : null;
        $this->container['marketingProductCode'] = isset($data['marketingProductCode']) ? $data['marketingProductCode'] : null;
        $this->container['orderInfo'] = isset($data['orderInfo']) ? $data['orderInfo'] : null;
        $this->container['merchantRequestIp'] = isset($data['merchantRequestIp']) ? $data['merchantRequestIp'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets appKey
     *
     * @return string
     */
    public function getAppKey()
    {
        return $this->container['appKey'];
    }

    /**
     * Sets appKey
     *
     * @param string $appKey appKey
     *
     * @return $this
     */
    public function setAppKey($appKey)
    {
        $this->container['appKey'] = $appKey;

        return $this;
    }

    /**
     * Gets yopMerchantNo
     *
     * @return string
     */
    public function getYopMerchantNo()
    {
        return $this->container['yopMerchantNo'];
    }

    /**
     * Sets yopMerchantNo
     *
     * @param string $yopMerchantNo yopMerchantNo
     *
     * @return $this
     */
    public function setYopMerchantNo($yopMerchantNo)
    {
        $this->container['yopMerchantNo'] = $yopMerchantNo;

        return $this;
    }

    /**
     * Gets parentMerchantNo
     *
     * @return string
     */
    public function getParentMerchantNo()
    {
        return $this->container['parentMerchantNo'];
    }

    /**
     * Sets parentMerchantNo
     *
     * @param string $parentMerchantNo parentMerchantNo
     *
     * @return $this
     */
    public function setParentMerchantNo($parentMerchantNo)
    {
        $this->container['parentMerchantNo'] = $parentMerchantNo;

        return $this;
    }

    /**
     * Gets merchantNo
     *
     * @return string
     */
    public function getMerchantNo()
    {
        return $this->container['merchantNo'];
    }

    /**
     * Sets merchantNo
     *
     * @param string $merchantNo merchantNo
     *
     * @return $this
     */
    public function setMerchantNo($merchantNo)
    {
        $this->container['merchantNo'] = $merchantNo;

        return $this;
    }

    /**
     * Gets payerMerchantNo
     *
     * @return string
     */
    public function getPayerMerchantNo()
    {
        return $this->container['payerMerchantNo'];
    }

    /**
     * Sets payerMerchantNo
     *
     * @param string $payerMerchantNo payerMerchantNo
     *
     * @return $this
     */
    public function setPayerMerchantNo($payerMerchantNo)
    {
        $this->container['payerMerchantNo'] = $payerMerchantNo;

        return $this;
    }

    /**
     * Gets marketingProductCode
     *
     * @return string
     */
    public function getMarketingProductCode()
    {
        return $this->container['marketingProductCode'];
    }

    /**
     * Sets marketingProductCode
     *
     * @param string $marketingProductCode marketingProductCode
     *
     * @return $this
     */
    public function setMarketingProductCode($marketingProductCode)
    {
        $this->container['marketingProductCode'] = $marketingProductCode;

        return $this;
    }

    /**
     * Gets orderInfo
     *
     * @return \Fy\Yeepay\Yop\Sdk\Service\Account\Model\EnterpriseAccountPayOrderOrderInfoDtoParam
     */
    public function getOrderInfo()
    {
        return $this->container['orderInfo'];
    }

    /**
     * Sets orderInfo
     *
     * @param \Fy\Yeepay\Yop\Sdk\Service\Account\Model\EnterpriseAccountPayOrderOrderInfoDtoParam $orderInfo orderInfo
     *
     * @return $this
     */
    public function setOrderInfo($orderInfo)
    {
        $this->container['orderInfo'] = $orderInfo;

        return $this;
    }

    /**
     * Gets merchantRequestIp
     *
     * @return string
     */
    public function getMerchantRequestIp()
    {
        return $this->container['merchantRequestIp'];
    }

    /**
     * Sets merchantRequestIp
     *
     * @param string $merchantRequestIp merchantRequestIp
     *
     * @return $this
     */
    public function setMerchantRequestIp($merchantRequestIp)
    {
        $this->container['merchantRequestIp'] = $merchantRequestIp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


